### ISSUE TITLE
Embargo for MR is needed?

### ISSUE THREAD

**Issue by Gasoid** [Gasoid/merge-bot#3]
check possibility to implement embargo period with https://github.com/ijt/go-anytime

example of new configuration parameters:
```yaml
embargo:
  - start: "18:05"
     end: "08:00"
  - start: "friday 18:00"
     end: "monday 08:00"
  - start: "25 dec"
     end: "02 jan"
```
